// Development-type category audit (issue #26, expansion Wave 0).
// WEDGE: The Sunday-night roofing DA digest for Sydney subbies.
//
// Scans development_applications and reports (a) the distinct development_type
// values we persist with counts, and (b) per-candidate-trade match rates
// (demolition / swimming pool / subdivision-earthworks, plus roofing baseline)
// — both via the free-text vocabulary the pipeline uses today and via the
// persisted category enum the expansion trade-pick (docs/25 §1.1) is betting on.
//
// Emits a Markdown report to stdout AND to docs/25b-development-type-audit.md
// (committed, "generated by" header + run date). The classification/count logic
// lives in the pure, fixture-tested src/modules/ingestion/development-type-audit.ts;
// this layer only owns the DB read + file write.
//
// Usage:
//   pnpm tsx scripts/audit-development-types.ts                 # run date = system clock
//   pnpm tsx scripts/audit-development-types.ts --date 2026-07-03
//   pnpm tsx scripts/audit-development-types.ts --out docs/25b-development-type-audit.md
//   pnpm tsx scripts/audit-development-types.ts --note "Sample run over seeded dev rows"
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { db } from "@/lib/db";
import {
  auditDevelopmentTypes,
  renderReport,
  type AuditRow,
} from "@/modules/ingestion/development-type-audit";

const GENERATED_BY = "scripts/audit-development-types.ts";
const DEFAULT_OUT = "docs/25b-development-type-audit.md";

/** Parse `--flag value` / `--flag=value` pairs from argv. */
function parseArgs(argv: string[]): { date?: string; out: string; note: string } {
  let date: string | undefined;
  let out = DEFAULT_OUT;
  let note = "";
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    const eq = arg.indexOf("=");
    const [key, inlineVal] = eq >= 0 ? [arg.slice(0, eq), arg.slice(eq + 1)] : [arg, undefined];
    const val = inlineVal ?? argv[++i];
    if (key === "--date") date = val;
    else if (key === "--out") out = val ?? DEFAULT_OUT;
    else if (key === "--note") note = val ?? "";
  }
  return { date, out, note };
}

/** yyyy-mm-dd for the run date. CLI arg wins; otherwise the system clock. */
function resolveRunDate(cliDate: string | undefined): string {
  if (cliDate) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(cliDate)) {
      throw new Error(`--date must be yyyy-mm-dd, got "${cliDate}"`);
    }
    return cliDate;
  }
  return new Date().toISOString().slice(0, 10);
}

async function main(): Promise<void> {
  const { date, out, note } = parseArgs(process.argv.slice(2));
  const runDate = resolveRunDate(date);

  const rows: AuditRow[] = await db.developmentApplication.findMany({
    select: { developmentType: true, description: true, rawScopeText: true },
  });

  const report = auditDevelopmentTypes(rows, runDate);
  const markdown = renderReport(report, GENERATED_BY, note);

  // Human-readable report to stdout.
  process.stdout.write(markdown + "\n");

  // Committed generated artifact.
  const outPath = resolve(process.cwd(), out);
  writeFileSync(outPath, markdown + "\n", "utf-8");
  console.error(`\n[audit] wrote ${out} (${report.totalRows} rows scanned)`);
}

main()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (err: unknown) => {
    console.error("[audit] fatal:", err);
    await db.$disconnect();
    process.exit(1);
  });
