-- WEDGE: Sunday-night roofing DA digest for Sydney subbies — keep relevance fast.
-- Adds (1) GIN tsvector index for keyword prefilter on DA scope/description,
--      (2) HNSW index for pgvector cosine ANN on saved-query and DA embeddings,
--      (3) GIN tsvector on raw_da.payload for ingestion-side dedupe scans.
-- Generated by db-migrator follow-up after backend-developer flagged the gap.

-- pg_trgm extension required for the trigram index below; declared first so DDL order is valid.
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- ── 1. GIN tsvector on development_applications (description + raw_scope_text)
ALTER TABLE "development_applications"
  ADD COLUMN IF NOT EXISTS "search_tsv" tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce("description", '')), 'A') ||
    setweight(to_tsvector('english', coalesce("raw_scope_text", '')), 'B')
  ) STORED;

CREATE INDEX IF NOT EXISTS "development_applications_search_tsv_idx"
  ON "development_applications" USING GIN ("search_tsv");

-- ── 2. HNSW indexes on pgvector embeddings (cosine distance, m=16, ef_construction=64)
-- Requires pgvector >= 0.5. Per docs/00-tech-stack.md: pgvector 0.7.
-- HNSW chosen over IVFFlat because the dataset is small enough (preview tier ≤ 100 users)
-- that build cost is trivial and recall@k is higher.

CREATE INDEX IF NOT EXISTS "da_embeddings_embedding_hnsw_idx"
  ON "da_embeddings" USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

CREATE INDEX IF NOT EXISTS "users_saved_query_embedding_hnsw_idx"
  ON "users" USING hnsw ("saved_query_embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ── 3. raw_da scope-text dedupe scan (cheap GIN on payload->>'description')
CREATE INDEX IF NOT EXISTS "raw_da_payload_description_trgm_idx"
  ON "raw_da" USING GIN ((payload->>'description') gin_trgm_ops);
